models: 
  - "VAE"
  - "BetaVAE"
  - "DVAE"
model_dir: "/home/everett/data/10-708-project-results/trained_models"
output_dir: "/home/everett/data/10-708-project-results/samples"
dataset_dir: "/home/everett/data"
datasets: 
  - "CIFAR10"
  - "MNIST"
  - "CelebA"
sampler: "NormalSampler"
metric: "FID"
num_samples: 10000
batch_size: 100
num_workers: 4

