models: 
  - "CRVAE"
model_dir: "/Users/andrewstange/Desktop/CMU/Spring_22/10-708/Project/aws_data/crvae_cifar10_all_augmentations"
output_dir: "/Users/andrewstange/Desktop/CMU/Spring_22/10-708/Project/samples"
dataset_dir: "/Users/andrewstange/Desktop/CMU/Spring_22/10-708/Project/datasets"
datasets: 
  - "CIFAR10"
sampler: "NormalSampler"
metric: "FID"
num_samples: 10000
batch_size: 100
num_workers: 4
calc_singular: False
lipschitz: False
curve_est: False
first_deriv: True
