models: 
  - "VAE"
  - "BetaVAE"
  - "DVAE"
model_dir: "/Users/andrewstange/Desktop/CMU/Spring_22/10-708/Project/10-708-project-results/trained_models"   # "/home/everett/data/10-708-project-results/trained_models"
output_dir: "/Users/andrewstange/Desktop/CMU/Spring_22/10-708/Project/samples" #"/home/everett/data/10-708-project-results/samples"
dataset_dir: "/home/everett/data"
datasets: 
  - "CIFAR10"
  - "MNIST"
sampler: "NormalSampler"
metric: "FID"
num_samples: 10000
batch_size: 100
num_workers: 4

