models: 
  # - "VAE"
  # - "BetaVAE"
  # - "DVAE"
  # - "DVAEAug"
  # - "CRVAE"
  - "PVAE"
model_dir: "./results/"
output_dir: "./samples"
dataset_dir: "./data"
datasets: 
  - "CIFAR10"
sampler: "NormalSampler"
metric: "FID"
num_samples: 10000
batch_size: 100
num_workers: 4
calc_singular: False
lipschitz: False
