models: 
  - "CRVAE"
model_dir: "./aws_data/trained_models/"
output_dir: "./samples"
dataset_dir: "./data"
datasets: 
  - "CelebA"
sampler: "NormalSampler"
metric: "FID"
num_samples: 3000
batch_size: 100
num_workers: 4
calc_singular: False
lipschitz: False
curve_est: False
