models: 
  - "VAE"
  - "BetaVAE"
  - "DVAE"
  - "CRVAE"
model_dir: "./aws_data/trained_models/"
output_dir: "./samples"
dataset_dir: "./data"
datasets: 
  - "CIFAR10"
  - "CelebA"
sampler: "NormalSampler"
metric: "FID"
num_samples: 10000
batch_size: 100
num_workers: 4
calc_singular: False
lipschitz: False
