datasets:
  - "CIFAR10"
  - "CIFAR100" 
  - "Flowers102"

model: "VAE" 

model_config:
  - latent_dim: 16

training_config:
  trainer_type : "BaseTrainer"
  output_dir: "./results"
  learning_rate: 0.001
  batch_size: 128
  num_epochs: 100
  seed: 42





  
